@host = http://localhost
@port = 5249
@Restaurants.API_HostAddress = https://localhost:7108


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Teste",
  "Description": "A great place to eat",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "contact@chesanyama.com",
  "ContactNumber": "067-456-7890",
  "City": "Seshego",
  "Street": "14A Main St",
  "PostalCode": "14-999"
}

###

GET https://localhost:7108/api/restaurants/20

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/16
Content-Type: application/json

{
  "Name": "sample patch2",
  "Description": "Restu description",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json

{
  "name": "Spaghetti Bolognese",
  "description": "Delicious pasta with meat sauce",
  "price": 12.99,
  "kilocalories": 800
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes/5

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/49/dishes

###

GET https://localhost:7108/api/restaurants/4/dishes/6

###

POST {{Restaurants.API_HostAddress}}/register
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Test@123"
}

###

POST {{Restaurants.API_HostAddress}}/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Test"
}